Public Enum GameEvent
	EVENT_NONE
	LOAD_GAME_MAIN
	LOAD_GAME_COLOR
	LOAD_GAME_CLIMBING
	LOAD_GAME_REGISTER
	LOAD_GAME_WORD_CONNECT
	LOAD_GAME_CIPHER
	LOAD_GAME_MAGIC_SQUARE
	LOAD_LEVEL_PARK_2
	EVENT_CLIMBING_GAME_COMPLETE
	EVENT_SLIDE_COMPLETE
	EVENT_MAGIC_SQUARE_COMPLETE
	LOAD_LEVEL_SEWERS_1
	LOAD_LEVEL_STREETS_1
	LOAD_LEVEL_PARK_1
	LOAD_LEVEL_MALL_1
	LOAD_LEVEL_MALL_2
	LOAD_LEVEL_MALL_3
	LOAD_LEVEL_BOOK_STORE
End Enum
